### ISSUE TITLE
ete显示总共的断言数量

### ISSUE THREAD

**Issue by Wesilnt** [onepiece-smile/docs#4]
当前ete断言数量显示只会显示到页面成功或者崩溃前的一次
![image](https://user-images.githubusercontent.com/27821997/149861878-ecb0fb08-fed6-4f0d-8f8b-ae91a9fa7506.png)
![image](https://user-images.githubusercontent.com/27821997/149861894-a65477ab-8b9e-4047-b79d-cfd424a3ff36.png)

**Comment by xflihaibo** [comment]
了解
